#!/bin/bash

echo "############################################## Vulnerability Report ##############################################"
echo "Generated in: " `date +%c`
echo " "
echo -e  "Vulnerability" \\t "Severity" \\t "Fix"
cat /var/log/zabbix/security-reports/vuln-report
echo "  "
echo "More details about the vulnerabilities and erratas: https://access.redhat.com/security/cve/cve-number"

